### PR TITLE
Changed Main website title

### PR DESCRIPTION
**Pull request by Daniul**
Changed the title to "Group 3's Favorite Movies" to reflect the addition of the Ops team into the website.

### CODE REVIEW

**Review by g308518 — APPROVED** [review]
looks good!

**Comment by Daniul** [comment]
> looks good!

Sounds good. I think you might have to approve the changes one more time. It still shows I still need an approving review.

**Review by g308518 — APPROVED** [review]
all good

**Review by g308518 — APPROVED** [review]
all good

**Review by g308518 — APPROVED** [review]
I think I had to press some other stuff but I am approving these changes!!

**Comment by g308518** [comment]
why isn't it working

**Review by Daniul — COMMENTED** [review]
My bad, approve this one instead.

**Comment by g308518** [comment]
I see the "review required" and i click on "add your review" and then i approve but

**Review by g308518 — APPROVED** [review]
does this work?

**Comment by g308518** [comment]
what am i doing wrong T-T

**Comment by g308518** [comment]
I have write access right?

**Comment by Daniul** [comment]
honestly im just gonna remove this review requirement thing. we'll just tell each other to comment anway

**Comment by g308518** [comment]
ok lol hopefully the prof is okay with that

**Comment by Daniul** [comment]
Yeah it should be okay. It's just that GitHub's settings for requiring approved changes is broken prob atm.

**Pull request merged**
