### PR TITLE
Updated to my favorite movies

### PR DESCRIPTION
**Pull request by StephenPursley**

### CODE REVIEW

**Comment by StephenPursley** [comment]
I also changed the title so it matched my 3 favorite movies rather than 3 movies that I watched recently

**Comment by Daniul** [comment]
Looks good! Actually let me fix something with your page real quick.

**Comment by Daniul** [comment]
Looks good! Merging to main

**Comment by StephenPursley** [comment]
Thank you! I was a bit worried that my changes might've caused an error.

**Pull request merged**
